### ISSUE TITLE
Using_sparkfun / SparkFun_MS5803-14BA_Breakout_with_TwoWire

### ISSUE THREAD

**Issue by simonlcparry** [sparkfun/SparkFun_MS5803-14BA_Breakout_Arduino_Library#4]
Please see my question in StackExchange:

https://stackoverflow.com/questions/62075710/is-there-a-way-to-modify-sparkfun-ms5803-i2c-cpp-h-to-allow-user-defined-non?noredirect=1#comment109907888_62075710

[RE Sparkfun-ms5803-i2c library     ref_00Do0aduJ._5001Jv06Mkref .pdf](https://github.com/sparkfun/SparkFun_MS5803-14BA_Breakout_Arduino_Library/files/4736422/RE.Sparkfun-ms5803-i2c.library.ref_00Do0aduJ._5001Jv06Mkref.pdf)

**Comment by PaulZC** [comment]
Hi Simon (@simonlcparry ),

Apologies for the _very_ slow reply! This is an old issue and a very old library... But we're still selling [MS5803 boards](https://www.sparkfun.com/products/12909), so it seems only right that we fix this.

The core issue is that this library is hard-coded to use ```Wire``` and only ```Wire```. The fix is to allow the ```TwoWire``` port to be passed in via ```begin```, but have it default to ```Wire```.

Fix coming shortly...

Best wishes,
Paul

**Comment by PaulZC** [comment]
Resolved in v1.1.3. Please see the updated example for details.
